codesydney/taskstech

src/index.js

This is for testing issue 7, etc.
- Issue Title
Issue #7

Issue 7 New Feature

---

.eslintignore
.eslintrc.json
.prettierignore
.prettierrc.json
package-lock.json
package.json
src/App.js
src/components/Forms/SignUp.js
src/components/Forms/TradieLogin.js
src/components/Forms/useForm.js
src/components/inventory/NewInventory.js
src/components/rightSideBar/RightSideBar.js
src/index.js

Install eslint and prettier in the code base
1. ```.eslintrc.json``` 
2. ```.prettierrc.json```
3. ``` .eslintignore```
4. ```.prettierignore```
1.  pull the PR to local repo 
2.  then ```npm instal```
3.  run ```npm start```
4. make sure compled successfully 
- before fix format
- compiled successfully
- Issue Title
n/a

Install eslint and prettier

---

src/actions/action.js
src/components/Jobs/CreateJob/CreateJob.js
src/components/Jobs/CreateJob/jobs.css
src/components/Jobs/ViewJobs/ViewJobs.js
src/components/rightSideBar/RightSideBar.js

Applied fix to navigation buttons.
npm install 
BUG_01_Navigation_Not_Working
- Issue Title

Fixed bug issue

---

src/actions/action.js
src/actions/actionTypes.js
src/components/Jobs/CreateJob/CreateJob.js
src/components/Jobs/CreateJob/jobs.css

Modified the create job ui that caters with mobile and desktop view using material ui's useMediaQuery media query hook.
npm install 
EP_04_01_Refactor_Job_Creation_UI
- Issue Title

Ep 04 01 refactor job creation UI

---

package-lock.json
src/actions/action.js
src/components/Jobs/CreateJob/CreateJob.js

This is for debug #48 
add an _if_ condition before the code block
````javascript
92 |                .then(res => {
93 |                   console.log(res)
94 |                   if (res.data.items){
95 |                   const items = res.data.items
96 |                   const inventoryList = []
97 |                 items.forEach(item => {
98 |                       const inventoryItem = item
99 |                       inventoryList.push(inventoryItem)
100 |                   })
101 |                   dispatch(fetchInventoryAction(inventoryList))}
102 |             })
````
- you should be able to login without seeing any error from browser
https://user-images.githubusercontent.com/36904351/135771650-743e59fd-54ca-44f5-8e38-6c6797209ea8.mov

Debug issue 48

---

src/common/Lookup.js
src/components/Jobs/CreateJob/CreateJob.js

Refactored the form validation. This code aims to fix unexpected behaviours of the previous validation code.
npm install 
Reimplement_Form_Validation

Reimplemented form validation

---

src/App.js
src/actions/action.js
src/actions/customerActions.js
src/components/Customer/CustomerProfile.jsx
src/pages/login/Login.jsx
src/pages/signUp/SignUp.jsx

npm install 
Add  alert messages for
-Customer Registration API Request
-Login API Request
-Sign-up API Request
Sorted Routes
-Sorted Routes by category
-Moved Customer Routes into Auth Routes

Error handling

---

src/App.js

Removed the duplicate render of job creation from the App.js file.
npm install 
- Issue Title

Remove duplicate form

---

src/components/inventory/InventoryDetail.js
src/components/inventory/setSerialArea.js
src/components/rightSideBar/RightSideBar.js

#62 inventory quantity

---

src/actions/action.js
src/actions/actionTypes.js
src/common/AlertModal.js
src/common/Lookup.js
src/components/Jobs/CreateJob/CreateJob.js
src/components/Jobs/CreateJob/jobs.css
src/components/Jobs/ViewJobs/ViewJobs.js
src/reducers/jobsReducer.js

Added an alert modal for create job and fixed scrollbar issue in Job View
npm install 
[[[Changes_in_Create_New_Job]()]()](https://github.com/codesydney/taskstech/issues/63)
- Issue Title

Added alert modal and fixed issue

---

src/actions/action.js
src/common/AlertModal.js
src/reducers/jobsReducer.js

Added a feature that redirects the user to the job view after the job has been created.
npm install 
- Issue Title

Made changes in job creation

---

src/components/Customer/CustomerRegistrationForm.jsx
src/components/Jobs/CreateJob/CreateJob.js
src/components/inventory/InventoryForm.jsx

Refactor create form layout

---

src/api/taskstechApi.js

Replaced the endpoint

---

src/components/Jobs/JobDiary/JobDiaryCards.js

Replaced endpoint in jobdiary cards

---

src/components/Jobs/CreateJob/CreateJob.js

Code cleanup

---

src/common/PhotoViewerDialog.js
src/components/Jobs/JobDiary/JobDiary.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/JobDiary/jobdiary.css

I've added the add activity button in the job diary accordion component to enable the user to add new job diary with the
current job.
npm install 
Add Activity Functionality in JobDiaryAccordions component 
https://github.com/codesydney/taskstech/issues/114
- Issue Title

Added add button in job diary accordion component

---

src/components/Jobs/JobDetails/JobDetails.js

I have fixed the CORS issue when attempting to update the job record. The cause of the issue is that the job id was not included in the jobObject when the code is dispatching the updateJob action creator.
npm install 
Updating the job doesn't work due to CORS error
- Issue Title

Fixed the CORS issue when updating the job.

---

src/App.js
src/actions/action.js
src/actions/activityAction.js
src/actions/photosActions.js
src/common/PhotoViewerDialog.js
src/components/Jobs/JobDiary/JobDiary.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/JobDiary/JobDiaryDetails.js
src/components/Jobs/ViewJobs/ControlledAccordions.js
src/components/Jobs/ViewJobs/FullWidthTabs.js
src/components/Jobs/ViewJobs/ViewJobs.js
src/components/Navigation/SwipeableEdgeDrawer.js
src/pages/LoginIndex.js

Fixed the routing issue with the login and job diary.
npm install 
https://github.com/codesydney/taskstech/issues/125
- Issue Title

Fixed url routing for job diary and mobile login.

---

src/common/FormDialog.js
src/components/Jobs/JobDiary/JobDiary.js
src/components/Navigation/SwipeableEdgeDrawer.js

Fixed issue with the id being undefined.

---

src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/ViewJobs/ControlledAccordions.js

Wrote a function that converts the UTC Time to Local Time.
1. Open the developer tools > Click the ... button displayed vertically > Click sensors > Select Tokyo
2. Edit the Job Diary and click submit
3. Check the current time at Tokyo and compare the last updated date of the diary(it should match).
npm install 
- Issue Title

Added a function convertUTCTimeToLocalTime

---

src/pages/LoginIndex.js

Removed margin from the LoginIndex component.

---

src/components/Jobs/JobDetails/JobDetails.js
src/components/Jobs/JobDiary/JobDiary.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/pages/LoginIndex.js

Fixed the layout issue of the job details and job diary.
npm install 
- Issue Title

fixed ui layout issue in job diary

---

src/actions/activityAction.js
src/components/Jobs/JobDiary/JobDiary.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/JobDiary/JobDiaryDetails.js

Fixed the internal server error when updating the activity id.

---

src/actions/photosActions.js
src/common/PhotoViewerDialog.js
src/components/Jobs/CreateJob/CreateJob.js
src/components/Jobs/JobDiary/JobDiaryDetails.js
src/reducers/photosReducer.js

Displays a photo template when the activity has no photo.

---

src/actions/photosActions.js
src/common/AlertModal.js
src/common/PhotoUploadDialog.js
src/common/PhotoViewerDialog.js
src/components/Jobs/CreateJob/CreateJob.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/JobDiary/JobDiaryCards.js
src/reducers/photosReducer.js

The most recent photo uploaded can now be viewed in the PhotoViewer component.
npm install 
The upload photo button does not work
- Issue Title
[[The upload photo button does not work]()](https://github.com/codesydney/taskstech/issues/120)

Bug upload photo does not work has been completed

---

src/App.js

The navigation bar should not be visible to the user during their login session. Because of this, I restructured the component
so that the navigation bar is only availabe to the user after they were successfully authenticated.
npm install 
Before:
After:
- Issue Title

Hid navigation bar while the user logs in and after logging out.

---

src/components/Jobs/CreateJob/CreateJob.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js

Fixed job ui

---

src/common/FormDialog.js

Replaced Dialog Title with Create New Diary

---

public/index.html
src/pages/login/Login.jsx
src/pages/login/login.css

Login component currently uses a legacy styling solution called makeStyle. I refactored the component to use css so that when it becomes fully deprecated on its next version release the web application would be functional.
n/a
Migrate Login component styles to plain css
- Issue Title
https://github.com/codesydney/taskstech/issues/152

Refactor migrate login component styles to plain css

---

src/pages/LoginIndex.js
src/pages/signUp/SignUp.jsx
src/pages/signUp/signup.css

Implement mobile view for mobile device

---

src/App.js
src/pages/LoginIndex.js
src/pages/signUp/SignUp.jsx

Added clear button that clears all the text field.
npm install 
- Issue Title

Added clear functionality

---

src/App.js
src/components/Jobs/ViewJobs/ControlledAccordions.js
src/components/Jobs/ViewJobs/DataTable.js
src/components/Jobs/ViewJobs/viewjobs.css
src/components/Navigation/RightSideBar.js
src/index.js

Summary
Undo recent changes with the right sidebar component due to the icons not showing up  in the web app.

Revert "Refactor migrate right sidebar component styles to plain css"

---

src/common/PhotoUploadDialog.js
src/common/PhotoViewerDialog.js
src/components/Jobs/JobDetails/JobDetails.js
src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/ViewJobs/ControlledAccordions.js
src/components/Jobs/ViewJobs/FullWidthTabs.js
src/pages/login/Login.jsx

Fixed the width of the photo preview image and the ui layout of the job, job diary.
npm install 
- Issue Title

Fixed the photo preview image and other ui issues

---

src/components/Jobs/JobDiary/JobDiaryAccordions.js
src/components/Jobs/JobDiary/jobdiary.css
src/components/Jobs/ViewJobs/ControlledAccordions.js

Changed the text alignment and font weight of the job diary contents.
npm install 
nil
[REFACTOR_UI_SET_THE_TEXT_ALIGNMENT_OF_ALL_THE_TEXT_JOB_DIARY](https://github.com/codesydney/taskstech/tree/REFACTOR_UI_SET_THE_TEXT_ALIGNMENT_OF_ALL_THE_TEXT_JOB_DIARY)
- Issue Title
[REFACTOR_UI_SET_THE_TEXT_ALIGNMENT_OF_ALL_THE_TEXT

Modified text alignment and font weight.
